### ISSUE TITLE
Guide is missing information/not working

### ISSUE THREAD

**Issue by sascha-wi** [Oku-Code/void-linux-guide#1]
I am hanging at the following point:

```
Entering chroot mode, you need mount the following files on to your system:
for dir in dev proc sys run; do mount --rbind /$dir /mnt/$dir; mount --make-rslave /mnt/$dir; done
```

System is complaining the mount point /mnt/dev does not exist

**Comment by sascha-wi** [comment]
I crosschecked with other installation guides did get past the error mentioned above, but even after that rebooting into void says wrong fs for tmpfs...really borked guide.

**Comment by Oku-Code** [comment]
Thanks for your feedback and taking your time to look it up at the guide

`Entering chroot mode, you need mount the following files on to your system:
for dir in dev proc sys run; do mount --rbind /$dir /mnt/$dir; mount --make-rslave /mnt/$dir; done`

In this, void linux handbook recommends to use the xchroot command, use this tool instead or check the [https://docs.voidlinux.org/config/containers-and-vms/chroot.html#manual-method](manual method) if you want to do manually and for the tmpfs directory you can check [https://docs.voidlinux.org/installation/guides/chroot.html#configure-fstab](tmpfs) part at the handbook or omit this part and continue with the process as well, this guide will be upgraded pretty soon with new info, this guide is quite updated.

_Sorry for the late response_.
